ALTER TABLE `sensors` ADD COLUMN IF NOT EXISTS `user_display` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' AFTER `current_val_2`;
ALTER TABLE `relays` ADD COLUMN IF NOT EXISTS `user_display` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' AFTER `lag_time`;
