DROP TABLE IF EXISTS `battery`;
CREATE TABLE IF NOT EXISTS `battery` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `node_id` char(50) COLLATE utf16_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf16 COLLATE=utf16_bin;
